# Q1. Platform-service使用邮箱地址mailmx.cyai.com进行邮件发送，提示错误如下：
```
platform-service email_handler.py email_worker(),Email request check paas
platform-service email_handler.py send_email(), Sending email connecting email server
连接邮箱地址错误。进入容器后ping mailmx.cyai.com发现地址无法访问，改成IP地址后可以正常访问，服务器也可以正常访问。那为什么容器内部不能访问呢？

A1：
服务器网络策略有过调整，服务器的dns更改过。导致paas集群内部记录dns信息旧的信息，未做更新(无法检测服务器dns更改)，需要手动重新启动网络插件。
操作步骤：登录PaaS-->进入集群-->选择System项目-->找到 coredns-autoscaler，coredns，canal 三个应用→重新部署
总结：
服务器dns解析正常，容器内部无法解析，先尝试重启集群网络插件。
```
# Q2. sso-db不清数据库 进行升级，会出现sso-db应用本身可以启动成功，但是不能对外暴露连接，外部是无法进行访问的？
```
A2：

问题难以复现，等之后遇到，再做分析
```
# Q3. k8s集群本身支持使用服务名的方式进行应用间交互操作，但是现在部署了公司内部的应用会出现dns解析的问题，也就是不支持服务名的方式访问？
```
分析1：参考郑勰的建议，初步分析是，应用依赖老的镜像基于ubuntu14作为基础镜像。。。可以尝试升级到最新版ubuntu-18进行测试验证

分析2：k8s部署依赖coredns插件版本低(概率很低，因为使用tomcat+nginx互相使用curl命令测试，并未发现异常)

A3:

1.升级业务应用基础镜像为18.04+

2.通过rancher升级k8s版本到1.16.3  和 coredns 1.6+  

问题修复者：郑勰  

参考链接：

https://coredns.io/2019/06/26/coredns-1.5.1-release/

https://github.com/coredns/coredns/pull/2885

https://github.com/coredns/coredns/pull/3573
```

# Q4. smes-db应用更新后，重启失败。提示如下错误信息:
```
FATAL: data directory "/var/lib/postgresql/data" has group or world access DETAIL: Permissions should be u=rwx (0700).

A4：登录到服务器，将/srv/docker/db/standard_mes-db  目录权限更改为700 chmod 700 /srv/docker/db/standard_mes-db
```

